// flow-typed signature: fdc926385a02d00a4fc64f875c786740
// flow-typed version: <<STUB>>/devtools-license-check_v^0.6.0/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'devtools-license-check'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'devtools-license-check' {
  declare module.exports: any;
}
